title: Umarani
author:
  name: 'Chintan Umarani'
  email: chintan4u@live.com
taxonomies:
  - tag
metadata:
  description: 'My Grav Site'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  /redirect-test: /
  '/old/(.*)': /new/$1
routes:
  /something/else: /blog/sample-3
  '/new/(.*)': /blog/$1
blog:
  route: /blog
